spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    com.travelsketch.travel: debug

jwt:
  secret: ${jwt.secret}

cloud:
  aws:
    credentials:
      access-key: ${s3.accessKey}
      secret-key: ${s3.secretKey}
    s3:
      bucket: travel-sketch-img-storage
    region:
      static: ap-northeast-2
    stack:
      auto: false